"""Add Diary model and update Message

Revision ID: dddbe2dd2268
Revises: 80188eef8ed3
Create Date: 2026-07-01 10:46:43.650453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dddbe2dd2268'
down_revision: Union[str, Sequence[str], None] = '80188eef8ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('core_emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('insight', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diaries_session_id'), 'diaries', ['session_id'], unique=False)
    op.add_column('messages', sa.Column('diary_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_messages_diary_id'), 'messages', ['diary_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'diaries', ['diary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_diary_id'), table_name='messages')
    op.drop_column('messages', 'diary_id')
    op.drop_index(op.f('ix_diaries_session_id'), table_name='diaries')
    op.drop_table('diaries')
    # ### end Alembic commands ###
